#!/usr/bin/env bash

# ==============================================================
#  Commit Lock System — Hook Installer
#
#  Run this from your PARENT REPO root:
#    bash /path/to/commit-lock-system/hooks/install-hooks.sh
#
#  Installs pre-commit and post-commit hooks into:
#    - The parent repo
#    - All submodules found in .gitmodules
# ==============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRE_COMMIT_SRC="${SCRIPT_DIR}/pre-commit"
POST_COMMIT_SRC="${SCRIPT_DIR}/post-commit"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
RESET='\033[0m'

ok()   { echo -e "  ${GREEN}[OK]${RESET}   $1"; }
warn() { echo -e "  ${YELLOW}[WARN]${RESET} $1"; }
skip() { echo -e "  ${YELLOW}[SKIP]${RESET} $1"; }
err()  { echo -e "  ${RED}[ERR]${RESET}  $1"; }

# ── Validate sources ──────────────────────────────────────────
if [ ! -f "$PRE_COMMIT_SRC" ]; then
  err "pre-commit hook not found at: $PRE_COMMIT_SRC"
  exit 1
fi

if [ ! -f "$POST_COMMIT_SRC" ]; then
  err "post-commit hook not found at: $POST_COMMIT_SRC"
  exit 1
fi

# ── Validate we're in a git repo ─────────────────────────────
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  err "Not a git repository. Run from the parent repo root."
  exit 1
fi

# ── Function: install hooks into one repo ───────────────────
install_hooks_to_repo() {
  local REPO_PATH="$1"
  local REPO_LABEL="$2"
  local HOOKS_DIR

  # Resolve .git/hooks path (handles submodules which use .git files)
  if [ -f "${REPO_PATH}/.git" ]; then
    # .git is a file (submodule) — read the actual git dir
    GIT_FILE_CONTENT=$(cat "${REPO_PATH}/.git")
    GIT_DIR=$(echo "$GIT_FILE_CONTENT" | sed 's/gitdir: //')
    # GIT_DIR is relative to REPO_PATH
    HOOKS_DIR="${REPO_PATH}/${GIT_DIR}/hooks"
    # Normalize path
    HOOKS_DIR=$(cd "${REPO_PATH}" && cd "${GIT_DIR}" && pwd)/hooks
  elif [ -d "${REPO_PATH}/.git" ]; then
    HOOKS_DIR="${REPO_PATH}/.git/hooks"
  else
    skip "$REPO_LABEL — .git not found (not initialized?)"
    return
  fi

  if [ ! -d "$HOOKS_DIR" ]; then
    mkdir -p "$HOOKS_DIR"
  fi

  # ── Install pre-commit ──────────────────────────────────────
  local PRE_DEST="${HOOKS_DIR}/pre-commit"
  if [ -f "$PRE_DEST" ]; then
    if grep -q "commit-lock" "$PRE_DEST" 2>/dev/null; then
      # Already ours — overwrite with latest version
      cp "$PRE_COMMIT_SRC" "$PRE_DEST"
      chmod +x "$PRE_DEST"
      ok "$REPO_LABEL — pre-commit updated"
    else
      # Existing hook from something else — chain
      warn "$REPO_LABEL — existing pre-commit found, chaining (backup: pre-commit.pre-lock-backup)"
      cp "$PRE_DEST" "${PRE_DEST}.pre-lock-backup"
      # Write a wrapper that calls our hook first, then the original
      {
        echo "#!/usr/bin/env bash"
        echo "# commit-lock wrapper (auto-generated by install-hooks.sh)"
        echo "# Original hook backed up as pre-commit.pre-lock-backup"
        echo ""
        cat "$PRE_COMMIT_SRC"
        echo ""
        echo "# Run original pre-commit hook"
        echo "\"${PRE_DEST}.pre-lock-backup\" \"\$@\""
      } > "$PRE_DEST"
      chmod +x "$PRE_DEST"
    fi
  else
    cp "$PRE_COMMIT_SRC" "$PRE_DEST"
    chmod +x "$PRE_DEST"
    ok "$REPO_LABEL — pre-commit installed"
  fi

  # ── Install post-commit ─────────────────────────────────────
  local POST_DEST="${HOOKS_DIR}/post-commit"
  if [ -f "$POST_DEST" ] && ! grep -q "commit-lock" "$POST_DEST" 2>/dev/null; then
    cp "$POST_DEST" "${POST_DEST}.pre-lock-backup"
    {
      echo "#!/usr/bin/env bash"
      echo "# commit-lock wrapper"
      echo ""
      cat "$POST_COMMIT_SRC"
      echo ""
      echo "\"${POST_DEST}.pre-lock-backup\" \"\$@\""
    } > "$POST_DEST"
    chmod +x "$POST_DEST"
  else
    cp "$POST_COMMIT_SRC" "$POST_DEST"
    chmod +x "$POST_DEST"
  fi
}

# ── Main ──────────────────────────────────────────────────────
echo ""
echo "======================================================="
echo "  Commit Lock System — Hook Installer"
echo "======================================================="
echo ""
echo "Installing into parent repo..."
install_hooks_to_repo "." "parent-repo"

# ── Install into all submodules ───────────────────────────────
if [ ! -f ".gitmodules" ]; then
  echo ""
  warn "No .gitmodules found — skipping submodule installation."
else
  echo ""
  echo "Installing into submodules..."

  # Read all submodule paths from .gitmodules
  while IFS= read -r line; do
    SUBMODULE_PATH=$(echo "$line" | awk '{print $2}')
    SUBMODULE_NAME=$(echo "$line" | sed 's/submodule\.\(.*\)\.path.*/\1/')

    if [ -z "$SUBMODULE_PATH" ]; then
      continue
    fi

    if [ -d "$SUBMODULE_PATH" ]; then
      install_hooks_to_repo "$SUBMODULE_PATH" "$SUBMODULE_NAME"
    else
      skip "$SUBMODULE_NAME — directory not found at '$SUBMODULE_PATH' (run: git submodule update --init)"
    fi
  done < <(git config --file .gitmodules --get-regexp path 2>/dev/null)
fi

# ── Summary ────────────────────────────────────────────────────
echo ""
echo "======================================================="
echo "  Installation complete!"
echo "======================================================="
echo ""
echo "NEXT STEPS for each developer:"
echo ""
echo "  1. Copy the config template to your home directory:"
echo "       cp .commit-lock-config.example ~/.commit-lock-config"
echo ""
echo "  2. Edit ~/.commit-lock-config and set:"
echo "       export COMMIT_LOCK_USER=\"your-username\""
echo "       export COMMIT_LOCK_SERVER=\"http://<server-ip>:3000\""
echo ""
echo "  3. Source it in your shell (add to ~/.bashrc or ~/.zshrc):"
echo "       source ~/.commit-lock-config"
echo ""
echo "  4. Open the dashboard in a pinned browser tab:"
echo "       http://<server-ip>:3000"
echo ""
